# Main site settings
title: Guava
subtitle: Google core libraries for Java
description: Google core libraries for Java
baseurl: /guava
url: http://google.github.io
permalink: /news/:year/:month/:day/:title/

markdown: kramdown

exclude:
- "Gemfile*"
- "README.md"
- "*.sh"

# Required on GitHub pages
safe: true
lsi: false

# Collections
collections:
 releases:
   output: true
   permalink: /:collection/:path/

# Miscellaneous data
email: guava-discuss@googlegroups.com
twitter_username: GoogleGuava
github_username:  google/guava
